name: GraphQL Api Clean Architecture

on:
  push:
    branches: ["main"]

jobs:
  generate_ssh_keys:
    name: Generate SSH Key Pair
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SSH Key Pair
        id: generate_ssh
        run: |
          ssh-keygen -t rsa -b 4096 -f ec2-ssh-key -N "" -C "github_actions@github.com"
          echo "::set-output name=private_key::$(cat ec2-ssh-key)"
          echo "::set-output name=public_key::$(cat ec2-ssh-key.pub)"

      - name: Save Private Key as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-private-key
          path: ec2-ssh-key

      - name: Save Public Key as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-public-key
          path: ec2-ssh-key.pub

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs: generate_ssh_keys

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SSH Key Pair Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ssh-private-key
          path: ./ssh-keys

      - name: Download Public Key Artifact
        uses: actions/download-artifact@v4
        with:
          name: ssh-public-key
          path: ./ssh-keys

      - name: Set Public Key as Environment Variable
        id: set_public_key
        run: echo "PUBLIC_KEY=$(cat ./ssh-keys/ec2-ssh-key.pub)" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

        with:
          terraform_version: 1.0.11

      - name: Initialize Terraform
        env:
          TF_VAR_public_key: ${{ env.PUBLIC_KEY }}
        run: terraform init
        working-directory: ci

    # - name: Plan Terraform
    #   env:
    #     TF_VAR_public_key: ${{ env.PUBLIC_KEY }}
    #   run: terraform plan

    # - name: Apply Terraform
    #   env:
    #     TF_VAR_public_key: ${{ env.PUBLIC_KEY }}
    #   run: terraform apply -auto-approve

    # - name: Save Terraform State
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: terraform-state
    #     path: ./terraform.tfstate

  # Deploy Node Application.
  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "20"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build project
  #       run: npm run build # Change this if you have a different build step

  #     - name: Upload SSH key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.EC2_SSH_KEY }}
  #         name: id_rsa
  #         known_hosts: ${{ secrets.EC2_HOST }}

  #     - name: Deploy to EC2
  #       env:
  #         EC2_USER: ${{ secrets.EC2_USER }}
  #         EC2_HOST: ${{ secrets.EC2_HOST }}
  #         EC2_PATH: ${{ secrets.EC2_PATH }}
  #       run: |
  #         ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "mkdir -p $EC2_PATH"
  #         rsync -avz --exclude 'node_modules' ./ $EC2_USER@$EC2_HOST:$EC2_PATH/
  #         ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
  #           cd $EC2_PATH &&
  #           npm install &&
  #           pm2 restart all || pm2 start app.js --name my-app
  #         "
