name: Setup AWS Infra (Terraform)

on:
  workflow_dispatch:

jobs:
  terraform:
    permissions: "write-all"
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_iam_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_aws_iam_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_ssh_ec2_public_key: ${{ secrets.AWS_EC2_PUBLIC_KEY }}
      TF_VAR_repository_name: ${{ vars.REPOSITORY_NAME }}
      TF_VAR_db_user: ${{ secrets.DATABASE_USER }}
      TF_VAR_db_password: ${{ secrets.DATABASE_PASSWORD }}

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          terraform_version: 1.1.7

      - name: Initialize Terraform
        run: terraform init
        working-directory: ci

      - name: Plan Terraform
        run: terraform plan -lock=false
        working-directory: ci

      - name: Apply Terraform
        run: terraform apply -auto-approve -lock=false
        working-directory: ci

      - name: Save EC2 IP to GitHub Secret
        working-directory: ci
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          EC2_PUBLIC_IP=$(terraform output public_ips | tr -d '"')
          AWS_DATABASE_HOST=$(terraform output database_host | tr -d '"')
          echo $EC2_PUBLIC_IP
          gh secret set EC2_PUBLIC_IP --body "$EC2_PUBLIC_IP" --repo ${{ github.repository }}
          gh secret set DATABASE_URL --body "postgres://$DATABASE_USER:$DATABASE_PASSWORD@$AWS_DATABASE_HOST:5432/postgres"
